--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PJZ9n/libasynql-Test
build-by-default: true
branches:
  - master
projects:
  libasynql-Test:
    libs:
      - src: poggit/libasynql/libasynql
        version: 3.2.0
...